[Behavior]
QuickExec=true
SingleClick=false

[Desktop]
Wallpaper=/usr/local/share/bluespark/wallpaper.png
WallpaperMode=zoom
BgColor=#0b1220
FgColor=#ffffff
ShadowColor=#000000
DesktopShortcuts=@Invalid()

[Volume]
AutoRun=false
CloseOnUnmount=true
MountOnStartup=false
MountRemovable=false
