[General]
__userfile__=true

[panel1]
plugins=fancymenu,quicklaunch,taskbar,statusnotifier,tray,mount,worldclock,showdesktop
position=Bottom
desktop=0
panelSize=40
iconSize=24

[fancymenu]
type=fancymenu
alignment=Left
filterClear=true
autoSel=true
autoSelDelay=150

[quicklaunch]
type=quicklaunch
alignment=Left
apps\1\desktop=/usr/share/applications/io.github.DannyS124.DiskForge.desktop
apps\2\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\3\desktop=/usr/share/applications/firefox-esr.desktop
apps\4\desktop=/usr/share/applications/qterminal.desktop
apps\size=4

[taskbar]
type=taskbar
buttonWidth=220
closeOnMiddleClick=true
groupingEnabled=false

[mount]
type=mount

[worldclock]
type=worldclock

[showdesktop]
alignment=Right
type=showdesktop

[statusnotifier]
alignment=Right
type=statusnotifier

[tray]
type=tray
